name: run-tests
run-name: Running tests as changes were pushed by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-app-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 15
          distribution: zulu
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Tests
        run: ./gradlew test
